-- MySQL Script generated by MySQL Workbench
-- Tue Sep 21 11:44:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema toeic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema toeic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `toeic` DEFAULT CHARACTER SET utf8 ;
USE `toeic` ;

-- -----------------------------------------------------
-- Table `toeic`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`account` (
  `accid` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`accid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `toeic`.`categorymember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`categorymember` (
  `categorymemberid` INT(11) NOT NULL,
  `categorymembername` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`categorymemberid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `toeic`.`grammarguideline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`grammarguideline` (
  `grammarguidelineid` INT(11) NOT NULL AUTO_INCREMENT,
  `grammarname` LONGTEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `grammarimage` VARCHAR(45) NULL DEFAULT NULL,
  `content` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`grammarguidelineid`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `toeic`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`member` (
  `memberid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `membername` VARCHAR(45) NULL DEFAULT NULL,
  `memberpass` VARCHAR(45) NULL DEFAULT NULL,
  `categorymemberid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`memberid`),
  INDEX `FK_MB_CMB_idx` (`categorymemberid` ASC) VISIBLE,
  CONSTRAINT `FK_MB_CMB`
    FOREIGN KEY (`categorymemberid`)
    REFERENCES `toeic`.`categorymember` (`categorymemberid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `toeic`.`cmtgrammar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`cmtgrammar` (
  `cmtgrammarid` INT(11) NOT NULL AUTO_INCREMENT,
  `cmtgrammarcontent` TEXT NULL DEFAULT NULL,
  `memberid` INT(11) NULL DEFAULT NULL,
  `grammarguidelineid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cmtgrammarid`),
  INDEX `FK_CMTGRA_GRAGU_idx` (`grammarguidelineid` ASC) VISIBLE,
  INDEX `FK_CMTGRA_ME_idx` (`memberid` ASC) VISIBLE,
  CONSTRAINT `FK_CMTGRA_GRAGU`
    FOREIGN KEY (`grammarguidelineid`)
    REFERENCES `toeic`.`grammarguideline` (`grammarguidelineid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CMTGRA_ME`
    FOREIGN KEY (`memberid`)
    REFERENCES `toeic`.`member` (`memberid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `toeic`.`vocabularyguideline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`vocabularyguideline` (
  `vocabularyguidelineid` INT(11) NOT NULL AUTO_INCREMENT,
  `vocabularyname` VARCHAR(45) NULL DEFAULT NULL,
  `vocabularyimage` VARCHAR(45) NULL DEFAULT NULL,
  `checknoidung` INT(11) NULL DEFAULT NULL,
  `checkaudiohinhanh` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`vocabularyguidelineid`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `toeic`.`cmtvocabulary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`cmtvocabulary` (
  `cmtvocabularyid` INT(11) NOT NULL AUTO_INCREMENT,
  `cmtvocabularycontent` TEXT NULL DEFAULT NULL,
  `memberid` INT(11) NULL DEFAULT NULL,
  `vocabularyguidelineid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cmtvocabularyid`),
  INDEX `FK_CMTVO_MEM_idx` (`memberid` ASC) VISIBLE,
  INDEX `FK_CMTVO_VOGU_idx` (`vocabularyguidelineid` ASC) VISIBLE,
  CONSTRAINT `FK_CMTVO_MEM`
    FOREIGN KEY (`memberid`)
    REFERENCES `toeic`.`member` (`memberid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CMTVO_VOGU`
    FOREIGN KEY (`vocabularyguidelineid`)
    REFERENCES `toeic`.`vocabularyguideline` (`vocabularyguidelineid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `toeic`.`examination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`examination` (
  `examinationid` INT(11) NOT NULL AUTO_INCREMENT,
  `examinationame` VARCHAR(45) NULL DEFAULT NULL,
  `examinatioimage` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `checkedcauhoi` INT(11) NULL DEFAULT NULL,
  `checkedaudiohinhanh` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`examinationid`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `toeic`.`examinationquestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`examinationquestion` (
  `examinationquestionid` INT(11) NOT NULL AUTO_INCREMENT,
  `num` INT(11) NULL DEFAULT NULL,
  `imagequestion` VARCHAR(45) CHARACTER SET 'ucs2' COLLATE 'ucs2_swedish_ci' NULL DEFAULT NULL,
  `audiogg` VARCHAR(45) CHARACTER SET 'ucs2' COLLATE 'ucs2_swedish_ci' NULL DEFAULT NULL,
  `audiomp3` VARCHAR(45) CHARACTER SET 'ucs2' COLLATE 'ucs2_swedish_ci' NULL DEFAULT NULL,
  `paragraph` TEXT CHARACTER SET 'ucs2' COLLATE 'ucs2_swedish_ci' NULL DEFAULT NULL,
  `question` TEXT CHARACTER SET 'ucs2' COLLATE 'ucs2_swedish_ci' NULL DEFAULT NULL,
  `option1` TEXT CHARACTER SET 'ucs2' COLLATE 'ucs2_swedish_ci' NULL DEFAULT NULL,
  `option2` TEXT CHARACTER SET 'ucs2' COLLATE 'ucs2_swedish_ci' NULL DEFAULT NULL,
  `option3` TEXT CHARACTER SET 'ucs2' COLLATE 'ucs2_swedish_ci' NULL DEFAULT NULL,
  `option4` TEXT CHARACTER SET 'ucs2' COLLATE 'ucs2_swedish_ci' NULL DEFAULT NULL,
  `correctanswer` VARCHAR(45) CHARACTER SET 'ucs2' COLLATE 'ucs2_swedish_ci' NULL DEFAULT NULL,
  `examinationid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`examinationquestionid`),
  INDEX `FK_EXQ_EX_idx` (`examinationid` ASC) VISIBLE,
  CONSTRAINT `FK_EXQ_EX`
    FOREIGN KEY (`examinationid`)
    REFERENCES `toeic`.`examination` (`examinationid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 141
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `toeic`.`listenexercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`listenexercise` (
  `listenexerciseid` INT(11) NOT NULL AUTO_INCREMENT,
  `listenexercisename` VARCHAR(45) NULL DEFAULT NULL,
  `listenexerciseimage` VARCHAR(45) NULL DEFAULT NULL,
  `checkcauhoi` INT(11) NULL DEFAULT NULL,
  `checkaudiohinhanh` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`listenexerciseid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `toeic`.`listenquestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`listenquestion` (
  `listenquestionid` INT(11) NOT NULL AUTO_INCREMENT,
  `num` INT(11) NULL DEFAULT NULL,
  `imagename` VARCHAR(45) NULL DEFAULT NULL,
  `audiomp3` VARCHAR(45) NULL DEFAULT NULL,
  `audiogg` VARCHAR(45) NULL DEFAULT NULL,
  `question` TEXT NULL DEFAULT NULL,
  `option1` TEXT NULL DEFAULT NULL,
  `option2` TEXT NULL DEFAULT NULL,
  `option3` TEXT NULL DEFAULT NULL,
  `option4` TEXT NULL DEFAULT NULL,
  `correctanswer` VARCHAR(45) NULL DEFAULT NULL,
  `listenexerciseid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`listenquestionid`),
  INDEX `FK_LIQU_LIEX_idx` (`listenexerciseid` ASC) VISIBLE,
  CONSTRAINT `FK_LIQU_LIEX`
    FOREIGN KEY (`listenexerciseid`)
    REFERENCES `toeic`.`listenexercise` (`listenexerciseid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `toeic`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`province` (
  `province_id` INT(11) NOT NULL,
  `province_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`province_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `toeic`.`readexercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`readexercise` (
  `readexeriseid` INT(11) NOT NULL AUTO_INCREMENT,
  `readname` VARCHAR(45) NULL DEFAULT NULL,
  `readimage` VARCHAR(45) NULL DEFAULT NULL,
  `checkcauhoi` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`readexeriseid`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `toeic`.`readquestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`readquestion` (
  `readquestionid` INT(11) NOT NULL AUTO_INCREMENT,
  `num` INT(11) NULL DEFAULT NULL,
  `paragraph` TEXT NULL DEFAULT NULL,
  `question` TEXT NULL DEFAULT NULL,
  `option1` TEXT NULL DEFAULT NULL,
  `option2` TEXT NULL DEFAULT NULL,
  `option3` TEXT NULL DEFAULT NULL,
  `option4` TEXT NULL DEFAULT NULL,
  `correctanswer` VARCHAR(45) NULL DEFAULT NULL,
  `readexeriseid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`readquestionid`),
  INDEX `FK_REQU_REEX_idx` (`readexeriseid` ASC) VISIBLE,
  CONSTRAINT `FK_REQU_REEX`
    FOREIGN KEY (`readexeriseid`)
    REFERENCES `toeic`.`readexercise` (`readexeriseid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `toeic`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`result` (
  `resultid` INT(11) NOT NULL AUTO_INCREMENT,
  `correctanswernum` INT(11) NULL DEFAULT NULL,
  `incorrectanswernum` INT(11) NULL DEFAULT NULL,
  `time` VARCHAR(50) NULL DEFAULT NULL,
  `examinationid` INT(11) NULL DEFAULT NULL,
  `memberid` INT(11) NULL DEFAULT NULL,
  `correctanswerread` INT(11) NULL DEFAULT NULL,
  `correctanswerlisten` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`resultid`),
  INDEX `FK_EX_RE_idx` (`memberid` ASC) VISIBLE,
  INDEX `FK_EX_RE_idx1` (`examinationid` ASC) VISIBLE,
  CONSTRAINT `FK_EX_RE`
    FOREIGN KEY (`examinationid`)
    REFERENCES `toeic`.`examination` (`examinationid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MEM_RE`
    FOREIGN KEY (`memberid`)
    REFERENCES `toeic`.`member` (`memberid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `toeic`.`slidebanner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`slidebanner` (
  `slidebannerid` INT(11) NOT NULL,
  `slidename` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `slidecontent` TEXT NULL DEFAULT NULL,
  `slideimage` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`slidebannerid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `toeic`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`student` (
  `student_id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_name` VARCHAR(45) NULL DEFAULT NULL,
  `province_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`student_id`),
  INDEX `FK_Student_Province_idx` (`province_id` ASC) VISIBLE,
  CONSTRAINT `FK_Student_Province`
    FOREIGN KEY (`province_id`)
    REFERENCES `toeic`.`province` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `toeic`.`vocabularycontent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toeic`.`vocabularycontent` (
  `vocabularycontentid` INT(11) NOT NULL AUTO_INCREMENT,
  `num` INT(11) NULL DEFAULT NULL,
  `vocabularycontentname` VARCHAR(45) NULL DEFAULT NULL,
  `transcribe` VARCHAR(45) NULL DEFAULT NULL,
  `image` VARCHAR(45) NULL DEFAULT NULL,
  `audiomp3` VARCHAR(45) NULL DEFAULT NULL,
  `audiogg` VARCHAR(45) NULL DEFAULT NULL,
  `mean` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `vocabularyguidelineid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`vocabularycontentid`),
  INDEX `FK_VOCO_VOGU_idx` (`vocabularyguidelineid` ASC) VISIBLE,
  CONSTRAINT `FK_VOCO_VOGU`
    FOREIGN KEY (`vocabularyguidelineid`)
    REFERENCES `toeic`.`vocabularyguideline` (`vocabularyguidelineid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
